# Generated by Django 3.0.6 on 2020-05-25 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='product_gtin',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='expiry date'),
            preserve_default=False,
        ),
    ]
